### PR TITLE
Chore/commitlint

### PR DESCRIPTION
**Pull request by breno-sapucaia**
Adding commilint dependecy in the root of monorepo in order to lint the commit messages from future contribuitions

### CODE REVIEW

**Review by danicunhac — CHANGES_REQUESTED** [review]
I've tested it locally and could commit without following a pattern. Can you test it again and make sure it fails to commit with the same phrase?

image

**Comment by breno-sapucaia** [comment]
@danicunhac  i unistall the husky and remake all the steps to configure but from a linux distro, and it worked when i cloned and tried commit anything out of the commitlint patterns, can you test again?

**Review by danicunhac — APPROVED** [review]
Great job! Could you try removing the test commits before we merge?

**Comment by danicunhac** [comment]
@all-contributors please add @breno-sapucaia for code

**Pull request merged**
