### PR TITLE
Add typography component

### PR DESCRIPTION
**Pull request by joaopaulomoraes**
## What is the reffered issue?

Issue: #53 

## What does this do?

typography-component-full

## What does it affect?

Add a new component with tests

## Any debts to pay? (optional)

No debt to be paid, however probably some components that currently have static text/typographic style will need to be updated to use this component.

## Review Checklist

- [x] Added and/or modified tests for affected areas
- [x] Ready to review
- [x] Ready to merge

### CODE REVIEW

**Comment by joaopaulomoraes** [comment]
For all heading elements, just specify the level using the `as` property and some default styles will be applied without the need for other props.

To modify the element's behavior, use the other props to do the job, or use any other element allowed by the `as` attribute.

A complete list of examples has been provided in the component's story.

**Review by CarmichaelF — APPROVED** [review]

**Review by CarmichaelF — CHANGES_REQUESTED** [review]
Please change the base to develop instead of main

**Comment by joaopaulomoraes** [comment]
Done!

**Comment by igorlourenco** [comment]
@joaopaulomoraes thanks for your contribution, merging

**Pull request merged**
